export const GET_CAT_REQUEST_ACTION = "CATS::GET_CAT_REQUEST_ACTION";
export const GET_CAT_SUCCESS_ACTION = "CATS::GET_CAT_SUCCESS_ACTION";
export const GET_CAT_FAILURE_ACTION = "CATS::GET_CAT_FAILURE_ACTION";
export const GET_PREVIOUS_CAT_ACTION = "CATS::GET_PREVIOUS_CAT_ACTION";
